# Generated by Django 4.0.5 on 2022-06-27 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supers_style', '0001_initial'),
        ('supers', '0002_supers_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supers',
            name='style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supers_style.supersstyle'),
            preserve_default=False,
        ),
    ]
